In [1]:
%cd /Users/carlosrobertofloresluna/Documents/0_Github/Capa_analitica_ecommerces_retail/entorno_dev

/Users/carlosrobertofloresluna/Documents/0_Github/Capa_analitica_ecommerces_retail/entorno_dev

### Lectura de datos en raw

In [15]:
from scripts.utils.file_utils import read_source

sources_to_test = [
    "catalogo_productos",
    "clientes_cdmx",
    "clientes_gdl_mty",
    "clientes_resto",
    "ordenes_2022_2023",
    "ordenes_2024",
]

for source_name in sources_to_test:
    print(f"\n📦 Leyendo fuente: {source_name}")
    df = read_source(source_name)
    print(f"Shape: {df.shape}")
    display(df.head(3))

📦 Leyendo fuente: catalogo_productos
Shape: (4500, 11)

,sku,nombre_producto,categoria_subcategoria,precio_lista,peso,proveedor,descripcion,stock_disponible,fecha_alta,activo,source_name
0,sku_00001,Ropa Mujer Purpose 865,Moda > Ropa Mujer,"$ 15,255.49",2.35 kg,"Coronado, Laureano y Marrero",Agent every development say quality throughout...,417.0,2019-02-03,1,catalogo_productos
1,SKU-00002,Ropa Mujer All 803,Moda > Ropa Mujer,"$ 9,093.43",20.88 kg,Ramos-Zamudio S.A. de C.V.,Despite measure ago current practice nation de...,297.0,2023-07-19,1,catalogo_productos
2,P-00003,Televisores Table 576,Electrónica > Televisores,"$ 17,942.43",2.93 kg,"Proyectos Villarreal, Corrales y Nava",NaN,454.0,2021-10-07,1,catalogo_productos

📦 Leyendo fuente: clientes_cdmx
Shape: (2667, 12)

,cliente_id,nombre,apellido_paterno_materno,email,genero,fecha_registro,estado,telefono,codigo_postal,activo_flag,alcaldía_municipio,source_name
0,CLI-000083,Jorge,Sosa Grijalva,qpuente@example.com,F,2021-09-20,Ciudad de México,81-5919-8154,98680.0,1,Iztapalapa,clientes_cdmx
1,CLI-000100,Cristobal,Zelaya Peralta,reinaguardado@example.com,F,2021-01-05,Ciudad de México,998-4596-4806,83275.0,1,Coyoacán,clientes_cdmx
2,CLI-000114,Marisol,Sanabria Arteaga,guadalupe60@example.com,M,2024-09-09,Ciudad de México,55-9196-8300,21781.0,1,Azcapotzalco,clientes_cdmx

📦 Leyendo fuente: clientes_gdl_mty
Shape: (5416, 11)

,customer_id,first_name,last_name,email_address,gender,registration_date,state,phone,zip_code,is_active,source_name
0,CLI-002684,Jacinto,Armas Peña,octaviopedroza@example.org,F,08/08/2024,Nuevo León,55-6336-0421,76509,True,clientes_gdl_mty
1,CLI-051143,Germán,Valdés Fonseca,sonia22@example.com,F,23/12/2020,Nuevo León,81-3801-8090 ext. 3033,19597,True,clientes_gdl_mty
2,CLI-048801,Pascual,Ojeda Mora,yolanda75@example.net,M,25/11/2019,Jalisco,998-0305-0405,97594,True,clientes_gdl_mty

📦 Leyendo fuente: clientes_resto
Shape: (45023, 10)

,cliente_id,email,genero,fecha_registro,estado,telefono,codigo_postal,activo_flag,nombre_completo,source_name
0,CLI-000001,salvadormoya@example.org,F,1640569780,Coahuila,81-1646-5630,85579,1.0,Silvia Abrego Toro,clientes_resto
1,CLI-000002,None,M,1622740734,Hidalgo,81-3058-9991,49211,1.0,Francisco Javier Leyva Dueñas,clientes_resto
2,CLI-000003,lzuniga@example.net,M,1670208934,San Luis Potosí,222-4779-2313,86234,1.0,Alvaro Rubio Maldonado,clientes_resto

📦 Leyendo fuente: ordenes_2022_2023
Shape: (500000, 10)

,order_id,id_cliente,sku_producto,canal_estatus,fecha_orden,monto_total,cantidad,direccion_entrega,fecha_actualizacion,source_name
0,ORD-0253632,CLI-008339,P-03419,Meli|confirmado,21-10-2023,6202.95,4,"Diagonal Pantoja 427 Edif. 931 , Depto. 732, N...",22/10/2023,ordenes_2022_2023
1,ORD-0077437,CLI-037806,03740,mercado libre|pagado,2023-07-02T13:47:58,6875.85,3,"Boulevard Zacatecas 983 Edif. 697 , Depto. 880...",02/07/2023,ordenes_2022_2023
2,ORD-0453072,CLI-050028,01239,MELI|APPROVED,2023/04/02,5594.08,2,"Pasaje México 430 Edif. 478 , Depto. 862, San ...",2023/04/03,ordenes_2022_2023

📦 Leyendo fuente: ordenes_2024
Shape: (280000, 12)

,orden_id,cliente_id,producto_sku,canal_venta,estatus_pago,fecha_compra,monto,cantidad_unidades,domicilio_entrega,descuento_aplicado,fecha_modificacion,source_name
0,ORD-0242895,CLI-052514,00352,mercadolibre,CONFIRMADO,2024-04-01,5235.78,3,"Circuito Sur Peña 101 Interior 874, Nueva Timo...",31.46,03 Apr 2024,ordenes_2024
1,ORD-0194402,CLI-024456,PROD-01488,amazon_mx,confirmado,2024/10/14,6721.74,1,"Boulevard Sur Tello 955 Edif. 464 , Depto. 309...",1183.99,2024/10/15,ordenes_2024
2,ORD-0287223,CLI-017172,03546,Meli,confirmado,2024-03-10,1836.41,5,"Avenida Micronesia 159 Edif. 920 , Depto. 770,...",0.00,2024/03/11,ordenes_2024

### Pruebas para STAGING : Limpieza estructural.

Creamos una capa técnica previa a **STAGING** usando Python para **leer, homologar y unificar múltiples archivos RAW por dominio**. Consolidamos **clientes (3 fuentes)**, **órdenes (2 fuentes)** y **catálogo (1 fuente)** en **DataFrames canónicos únicos**, listos para persistirse en **SQLite** y ser consumidos por **dbt** como fuentes STAGING limpias, trazables y reutilizables.

In [16]:
from scripts.ingestion.unify_clientes import unify_clientes
from scripts.ingestion.unify_ordenes import unify_ordenes

df_clientes_cdmx = read_source("clientes_cdmx")
df_clientes_gdl = read_source("clientes_gdl_mty")
df_clientes_resto = read_source("clientes_resto")

df_clientes = unify_clientes(df_clientes_cdmx, df_clientes_gdl, df_clientes_resto)

#Validacion de registros hace match con el número de registros desde raw.
df_clientes.groupby("source_name").count()

,cliente_id,nombre,apellido,nombre_completo,email,genero,fecha_registro,estado,telefono,extension_telefono,codigo_postal,activo_flag,municipio
source_name,,,,,,,,,,,,,
clientes_cdmx,2667,2667,2667,2667,2589,2251,2667,2667,2667,0,2498,2667,2667
clientes_gdl_mty,5416,5416,5416,5416,5191,4606,5416,5416,5416,1358,5234,5416,0
clientes_resto,45023,45023,45023,45023,42768,37693,45023,45023,45023,11295,45023,45023,0

In [17]:
df_orders_hist = read_source("ordenes_2022_2023")
df_orders_2024 = read_source("ordenes_2024")

df_ordenes = unify_ordenes(df_orders_hist, df_orders_2024)

df_ordenes.groupby("source_name").count()

,order_id,cliente_id,sku_producto,canal_venta,estatus_pago,fecha_orden,monto_total,cantidad,direccion_entrega,descuento_aplicado,fecha_actualizacion
source_name,,,,,,,,,,,
ordenes_2022_2023,500000,500000,500000,500000,500000,500000,490058,500000,500000,500000,500000
ordenes_2024,280000,280000,280000,280000,280000,280000,274334,280000,280000,280000,280000

In [18]:
df_catalogos = read_source("catalogo_productos")

df_catalogos.head(1)

,sku,nombre_producto,categoria_subcategoria,precio_lista,peso,proveedor,descripcion,stock_disponible,fecha_alta,activo,source_name
0,sku_00001,Ropa Mujer Purpose 865,Moda > Ropa Mujer,"$ 15,255.49",2.35 kg,"Coronado, Laureano y Marrero",Agent every development say quality throughout...,417.0,2019-02-03,1,catalogo_productos

## Capa INTERMEDIATE

Unificación de fragmentos, joins entre entidades, aplicación de reglas de negocio. Modelos reutilizables.

In [ ]:
#Faltaron los datos de devolución.

#Regla 3: Clasificación de Razón de Devolución

In [20]:
#Regla 4: Definición de Cliente Activo
#Regla 5: Segmentación de Valor de Cliente
#Regla 7: Cliente Recurrente

df_clientes.head()

,cliente_id,nombre,apellido,nombre_completo,email,genero,fecha_registro,estado,telefono,extension_telefono,codigo_postal,activo_flag,municipio,source_name
0,CLI-000083,Jorge,Sosa Grijalva,Jorge Sosa Grijalva,qpuente@example.com,F,2021-09-20,Ciudad de México,81-5919-8154,<NA>,98680,1,Iztapalapa,clientes_cdmx
1,CLI-000100,Cristobal,Zelaya Peralta,Cristobal Zelaya Peralta,reinaguardado@example.com,F,2021-01-05,Ciudad de México,998-4596-4806,<NA>,83275,1,Coyoacán,clientes_cdmx
2,CLI-000114,Marisol,Sanabria Arteaga,Marisol Sanabria Arteaga,guadalupe60@example.com,M,2024-09-09,Ciudad de México,55-9196-8300,<NA>,21781,1,Azcapotzalco,clientes_cdmx
3,CLI-000133,Norma,de la Torre Tovar,Norma de la Torre Tovar,lopezclemente@example.org,F,2019-12-04,Ciudad de México,442-4794-7503,<NA>,14667,1,Tlalpan,clientes_cdmx
4,CLI-000139,Lourdes,Cervantes Cortez,Lourdes Cervantes Cortez,estela98@example.org,F,2020-10-24,Ciudad de México,998-9118-7968,<NA>,70088,1,Gustavo A. Madero,clientes_cdmx

In [24]:
#Regla 1: Validez de una Orden
#Regla 2: Normalización de Canal de Venta
#Regla 6: Registro Canónico de una Orden

df_ordenes.head()

,order_id,cliente_id,sku_producto,canal_venta,estatus_pago,fecha_orden,monto_total,cantidad,direccion_entrega,descuento_aplicado,fecha_actualizacion,source_name
0,ORD-0253632,CLI-008339,P-03419,meli,confirmado,2023-10-21 00:00:00,6202.95,4,"Diagonal Pantoja 427 Edif. 931 , Depto. 732, N...",0.0,2023-10-22,ordenes_2022_2023
1,ORD-0077437,CLI-037806,03740,mercado libre,pagado,2023-07-02 13:47:58,6875.85,3,"Boulevard Zacatecas 983 Edif. 697 , Depto. 880...",0.0,2023-02-07,ordenes_2022_2023
2,ORD-0453072,CLI-050028,01239,meli,approved,2023-04-02 00:00:00,5594.08,2,"Pasaje México 430 Edif. 478 , Depto. 862, San ...",0.0,2023-04-03,ordenes_2022_2023
3,ORD-0124991,CLI-002277,sku_01752,meli,approved,2022-05-20 00:00:00,7806.20,1,"Pasaje Islandia 113 Edif. 477 , Depto. 249, Vi...",0.0,2022-05-22,ordenes_2022_2023
4,ORD-0236174,CLI-020045,SKU-04218,tienda,pending,2022-11-06 00:00:00,6101.06,4,"Calle Distrito Federal 277 Interior 674, Vieja...",0.0,2022-11-07,ordenes_2022_2023

In [25]:
df_catalogos.head()

,sku,nombre_producto,categoria_subcategoria,precio_lista,peso,proveedor,descripcion,stock_disponible,fecha_alta,activo,source_name
0,sku_00001,Ropa Mujer Purpose 865,Moda > Ropa Mujer,"$ 15,255.49",2.35 kg,"Coronado, Laureano y Marrero",Agent every development say quality throughout...,417.0,2019-02-03,1,catalogo_productos
1,SKU-00002,Ropa Mujer All 803,Moda > Ropa Mujer,"$ 9,093.43",20.88 kg,Ramos-Zamudio S.A. de C.V.,Despite measure ago current practice nation de...,297.0,2023-07-19,1,catalogo_productos
2,P-00003,Televisores Table 576,Electrónica > Televisores,"$ 17,942.43",2.93 kg,"Proyectos Villarreal, Corrales y Nava",NaN,454.0,2021-10-07,1,catalogo_productos
3,PROD-00004,Ropa Hombre True 263,Moda > Ropa Hombre,"$ 19,198.37",7.74 kg,"Nieto, Gaitán y Meraz",Serve civil institution everyone democratic sh...,334.0,2020-02-09,0,catalogo_productos
4,sku_00005,Accesorios Moda Husband 745,Moda > Accesorios Moda,"$ 3,584.69",23.21 kg,Robles S.A.,Grow gas enough analysis least by two bad.,140.0,2021-03-04,0,catalogo_productos

## CAPA MARTS 

Tablas finales optimizadas para consumo. El equipo de BI solo conecta aquí. Sin transformaciones adicionales.